### ISSUE TITLE
Clarify execute API endpoint

### ISSUE THREAD

**Issue by nichtich** [Project-KONDA/pattern-based-quality-analysis#2]
API endpoint [/constraint/execute/{technology}](https://github.com/Project-KONDA/pattern-based-quality-analysis/blob/master/qualitypatternmodel/openapi.yaml#L820) is the central method to run analysis. Its parameters are

- `files`: links to files to be analyzed
- `constraintIDs`: identifier of existing constraints to check on the files
- `constraints`: links to files to be analyzed

What's a "link"? An URL? A local filename? A full file path, relative to what?

Description of `constraints` seems to be wrong. How does this parameter relate to `constraintId`? What if both are given?

The result format also requires some more documentation

- What are "incident", "finding", "compliance"? Best explain with an example
- Objects in arrays "failedFiles" and "failedConstraint" actually look like `{"<parameter>":"..."}` or is `<parameter>` a placeholder for something?

**Comment by kespera** [comment]
the `files` parameter is supposed to be a relative path to the FILES_VOLUME (environmental variable). 

regarding `constraints` and  `constraintIDs`:
- input of the `constraints` parameter are compiled Query object: 
with `/constraint/query/{technology}/{constraintID}` a constraint can be compiled into a Query object. they shall enable the use of other query processors
- `constraintID` are uncompiled constraints referenced by ID. for the analysis they are compiled to queries internally
-  `constraints` and  `constraintIDs` do not exclude, but supplement each other: an analysis can combine compiled constraint and uncompiled constraints via ID
-  for a quality analysis at least one constraintID or one compiled constraint must be specified

documentation updated in both cases
