### ISSUE TITLE
Document constraint

### ISSUE THREAD

**Issue by nichtich** [Project-KONDA/pattern-based-quality-analysis#3]
The "constraint" object (as returned by API call `/constraint/{technology}/{constraintID}`) seems to be the central object type. It requires some documentation. It's [formal schema](https://github.com/Project-KONDA/pattern-based-quality-analysis/blob/master/qualitypatternmodel/openapi.yaml#L996) is called "pattern" instead of "constraint" and it contains a "language" instead of "technology", so some cleanup of terminology seems to be needed first.

**Comment by kespera** [comment]
- added documentation in general
- added some explanation to the `Pattern` schema: patterns is the central object of QPM, that can represent both templates and constraints. The resulting JSON structure is largely equal. Differences are added in the document.
- Added short text for the API call group `/constraint/{technology}/{constraintID}`
- changed language to technology (except for the query object, that is supposed to hold the query language, which currently is either XQuery, SPARQL or Cypher)
