### ISSUE TITLE
Server OpenAPI specification via HTTP

### ISSUE THREAD

**Issue by nichtich** [Project-KONDA/pattern-based-quality-analysis#5]
`/` should serve or link to the openapi specification file for easy import into [Postman](https://www.postman.com/) or similar tool. For instance serve at `/openapi.yaml` and brief info page instead of 404 at `/`.

**Comment by kespera** [comment]
The project currently gets deployed as qualitypatternmodel.war on a tomcat server. This results in the namespace `qualitypatternmodel` and consequently into `http://localhost:8080/qualitypatternmodel` as the base URL with all API calls adhering to this. For `http://localhost:8080/qualitypatternmodel` a basic Website already exists.
I can change the namespace by renaming the war file into ROOT.war before deploying. This would remove `qualitypatternmodel` from all URLs, which would require changes in Constrainify.

**Comment by kespera** [comment]
Additionally to preserve the behavior i could add a redirection from `/qualitypatternmodel/*` to `/*` but this could lead to confusion.

**Comment by nichtich** [comment]
Adding a redirection would help to avoid 404 errors for existing links. Removal of `/qualitypatternmodel` in the canonical path would also simplify API documentation.

**Comment by kespera** [comment]
I tend to just eliminate the namespace.
I already realized that in the development branch associated to this issue and updated the API documentation accordingly.
To merge it onto the main branch an update to constrainify would be necessary.

Currently the base call only shows a base Http-website.
Regarding the API specification, a `/docs` page would be appropriate in the future.

**Comment by kespera** [comment]
I updated the repository by removing the namespace all together. There is no redirection to `/qualitypatternmodel`. Constrainify will be adapted to this shortly.
The openapi specification now can be requested via `/docs`.
Further, `/`, `/health` and `/status` are added to check on the status of the QPM API.
